### ISSUE TITLE
question: maintainability and reproducability

### ISSUE THREAD

**Issue by dbu** [phpcr/phpcr-api-tests#154]
while reviewing some bugfixes for jackalope 1.1 i noticed that the master version of phpcr-api-tests fails with the jackalope-jackrabbit 1.1 branch because some more complicated fixes/changes went only to master.

this makes me wonder if we should tag the tests basically whenever we add a new test and make the jackalopes reference a specific tag (and frequently bump the tag we reference, of course). this will mean a bit more overhead to manage, but the current situation is that phpcr implementations try to match a moving target with the api tests. thoughts?

**Comment by dbu** [comment]
oh, i see that this seems to be the approach taken by @WouterJ in https://github.com/jackalope/jackalope-jackrabbit/pull/105

**Comment by WouterJ** [comment]
Now we have loweat dep tests, the problem is even worse: each implementation now has to be based on an exact version, as both older and newer versions have a high risk in making the build fail.

This, imo, clearly illistrate that this is not the way to solve it. But I don't have any better idea. In fact, the only other spec -> implementation library that I know (Mink) uses this way to.

**Comment by dbu** [comment]
so we go with a specific version
